### PR TITLE
Automatically trigger e2e test on PRs.

### PR DESCRIPTION
**Pull request by ericgraf**
This PR:
Automatically triggers E2e tests on new PRs.

Issue: https://github.com/giantswarm/giantswarm/issues/29379

### CODE REVIEW

**Review by glitchcrab — APPROVED** [review]
this is sexy

**Review by vxav — CHANGES_REQUESTED** [review]
Not 100% sure about this given https://github.com/giantswarm/giantswarm/issues/29539

Ping @AverageMarcus

**Comment by AverageMarcus** [comment]
Yeah, lets wait until after we've got some more resources to merge this in.

But thinking about it, this might actually end up _helping_ as it would run the tests as soon as the PR is created and not when someone in the team gets around to looking at it (which I suspect they will do at the same time as other PRs) 🤔

**Comment by glitchcrab** [comment]
i'm going to go ahead and merge this in as i'm working my way through clearing up the outstanding PRs here - we've had a storage bump so that shouldn't block us now.

**Pull request merged**
