### PR TITLE
add VCD cloud-provider app

### PR DESCRIPTION
**Pull request by glitchcrab**
This PR:

- adds `cloud-provider-cloud-director` app at v0.1.0

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Comment by vxav** [comment]
At the moment the CPI and CSI are installed as part of cloud-init, adding it into default apps maybe bring weird behaviour if they're already installed?

**Comment by glitchcrab** [comment]
Oh yes, I forgot about that issue. Let's leave this PR sitting for the moment then - we can release it at a later date

**Comment by vxav** [comment]
Cool, I'll convert it to draft in the meantime.

**Comment by vxav** [comment]
Outdated, will create a new one

**Pull request closed without merging**
